### ISSUE TITLE
lesson3 爬优酷的时候出现的问题

### ISSUE THREAD

**Issue by izayl** [alsotang/node-lessons#101]
Error: connect ECONNREFUSED
   at exports._errnoException (util.js:746:11)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)

**Comment by aimer1124** [comment]
@izayl 可以啊。

- 抓取
```
<div class="yk-logo">
				<a href="http://www.youku.com/" title="Youku 优酷" attr="idx0"><img src="http://static.youku.com/youku/dist/img/find/yk-logo-0412.png" width="140" height="50" alt="Youku 优酷" from="index"></a>
			</div>
```
- 代码

```

app.get('/', function (req, res, next) {
    superagent.get('http://www.youku.com/')
        .end(function (err, sres) {
            if (err) {
                return next(err);
            }
            var $ = cheerio.load(sres.text);
            res.send($('.yk-logo').find('a').attr('title'));
        });
});

```

- 结果
`Youku 优酷`

**Comment by sfsoul** [comment]
Error: connect ETIMEDOUT 106.11.186.3:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)


请问我一直报这个错需要怎么解决啊！！！
