### ISSUE TITLE
lesson6 istanbul报错

### ISSUE THREAD

**Issue by zhishaofei3** [alsotang/node-lessons#5]
我$ mocha的时候 没有问题 但是装了istanbul后用它却出现
E:\nodejs\lesson6>istanbul cover _mocha

C:\Users\Administrator\AppData\Roaming\npm_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
No coverage information was collected, exit without writing coverage information
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (C:\Users\Administrator\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:114:16)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:232:17
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:56:16
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:35:9

新建了一个文件夹 coverage ，但是不知道为什么报了错

**Comment by gejiawen** [comment]
@dayday89 能解析下为何要加上相对路径么？使用全局安装的mocha就会报错呢

**Comment by alextzh** [comment]
需要执行npm install mocha istanbul --save-dev,OK解决
