### ISSUE TITLE
lesson2 无法运行

### ISSUE THREAD

**Issue by shaowei-su** [alsotang/node-lessons#52]
你好，
按照教程出现报错：

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/Users/shaowei/NodeJsStudy/lesson2/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/shaowei/NodeJsStudy/lesson2/app.js:24:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

希望有空解答一下， 多谢。

**Comment by shaowei-su** [comment]
找到原因了，抱歉我真的是零基础。
之前listen了3000端口， ctrl + c并没有退出只是后台挂起了。

**Comment by alsotang** [comment]
嗯嗯，不过按理说 ctrl + c 应该是会退出而不是挂起的。

2015-08-12 12:59 GMT+08:00 Shaowei Su <notifications@github.com>:

**Comment by shaowei-su** [comment]
你好，
访问 https://cnodejs.org/ 时候提示Not Found. Resolve Domain Error. 
但是https://cnodejs.org/getstart可以正常访问。 

是我打开方式不对吗

谢谢

**Comment by alsotang** [comment]
目前正在备案，只有已登录用户可以访问。访客都屏蔽了

2015-08-12 13:15 GMT+08:00 Shaowei Su <notifications@github.com>:

**Comment by shaowei-su** [comment]
了解，多谢
